# Generated by Django 4.0.4 on 2022-04-29 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_alter_expense_options_alter_expense_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'РУбрики',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='expense.rubric', verbose_name='Рубрика'),
        ),
    ]
