# Generated by Django 4.0.4 on 2022-05-17 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_rubric_expense_rubric'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubric',
            options={'ordering': ['name'], 'verbose_name': 'Рубрику', 'verbose_name_plural': 'Рубрики'},
        ),
    ]
